### ISSUE TITLE
Register fatal with "unauthorized request reason"

### ISSUE THREAD

**Issue by lancatlin** [bitmark-inc/bitmark-sdk-go#13]
When I run `asset.Register`, it met this error: 
`[0] message: unauthorized request reason`

I don't know what happend, the go doc doesn't record this, either.  

``` go
assetID, err = asset.Register(params)
```

full code can see in [my repo](https://github.com/lancatlin/bitmark-issuer/blob/master/assets.go)

**Comment by nodestory** [comment]
Did you configure the API token for the Bitmark SDK? This error results from missing or invalid api token.

**Comment by lancatlin** [comment]
sorry, I forgot to set it in my .env file
