### ISSUE TITLE
[SDK-GO] Negative quantity is converted to 1 during bitmark issuance

### ISSUE THREAD

**Issue by vienlt** [bitmark-inc/bitmark-sdk-go#16]
**Action**: Issue bitmarks with entering a negative quantity (i.e. -3 ).
**Result**: The issuance is successful with quantity is converted to be `1`
**Expected Result**: Invalid quantity error is returned.

**Comment by nodestory** [comment]
Fixed at f075de2

**Comment by vienlt** [comment]
Tested and passed on https://github.com/bitmark-inc/bitmark-sdk-go/commit/3b0b9819cb0b73e3f99d18f36711b966c48443f5
