### ISSUE TITLE
[SDK-GO] Run time error returned while validating an invalid account number containing invalid letters

### ISSUE THREAD

**Issue by vienlt** [bitmark-inc/bitmark-sdk-go#17]
- Action: Validating an account number

- Input: Invalid account number which contains invalid letters as I, O, l

- Result: Run time error

- Expected result: The case is handled.

**Comment by nodestory** [comment]
Fixed at 3b0b981

**Comment by vienlt** [comment]
Tested on https://github.com/bitmark-inc/bitmark-sdk-go/commit/3b0b9819cb0b73e3f99d18f36711b966c48443f5 - passed.
