### ISSUE TITLE
[SDK-Go] Queries related issues

### ISSUE THREAD

**Issue by vienlt** [bitmark-inc/bitmark-sdk-go#4]
- [x] Infinite loop while querying **transactions** with **transient**

- [x] isPending option isn't available for any queries (asset, bitmark, transaction)

- [x] Limit size option doesn't work. It returns all records even when users send a query request with setting the limit size option

- [x] Sometime the following error is returned while querying for transactions

> [7000] message: internal server error reason: failed to query transactions because of error: sql: Scan error on column index 8, name "tx_block_number": converting driver.Value type int64 ("-1") to a uint64: invalid syntax

**Comment by nodestory** [comment]
The last error comes from the API side. It's fixed on the server instead.

**Comment by nodestory** [comment]
Fixed at: 2017c201d3f42b0d067c935b01106f694ea08ec3

**Comment by vienlt** [comment]
@nodestory: Some comments related to changes in the query interfaces

1. Should remove the `Asset       *asset.Asset ` in the Bitmark object since it is now used for nothing
2. Do we have anywhere to mention the deprecated interfaces? I saw some interfaces changed for the returned objects and also the number of variables. I.e. 
 + Interface to get bitmark from bitmarkid (before there are 2 params & 2 returned objects, now 1 param & 3 returned object)
 + New interface of getting bitmark from bitmarkid with Asset
 + Register asset from data interface is removed
 + Update text from `Id` to `ID`
 + List bitmarks & transactions from query param: returned objects changed from 2 to 3
 + Query params `OwnedBy` interface updated from 2 params (owner & transient) to 2 different interfaces with one param (owner)
 + ...

**Comment by nodestory** [comment]
Asset field is removed for both `Bitmark` and `Tx` structs at 6a3d572

**Comment by vienlt** [comment]
> Asset field is removed for both `Bitmark` and `Tx` structs at [6a3d572](https://github.com/bitmark-inc/bitmark-sdk-go/commit/6a3d572e9516a512d8e4fdb0a71fd3376374d07b)

Verified!

**Comment by vienlt** [comment]
Tested on the latest commit `d873e18cd84d` - All pased!
