### ISSUE TITLE
[SDK-Go] Two-signature transfer related issues

### ISSUE THREAD

**Issue by vienlt** [bitmark-inc/bitmark-sdk-go#5]
- [x] It doesn't check the recipient account's network while generating a transfer offer. It returns a success in case users generate a transfer offer to another network's account (i.e. testnet to livenet).

- [x] No error is returned and also nothing is changed in case of canceling or rejecting a transfer offer with signing the request by a wrong account.

- [x] Accept, reject, cancel transfer offer without sign the records => return unexpected api response (need another clearer error)

**Comment by nodestory** [comment]
`NewTransferParams` and `NewOfferParams` now also return error if the provided receiver is from different network.

**Comment by araujobsd** [comment]
Could you copy and past the commit hash here for reference? Also if this issue is done, we can close it.

**Comment by nodestory** [comment]
Fixed at: d28e26d7123f71cf3f7e4bd8232c994b61c48a94

**Comment by vienlt** [comment]
@nodestory: For problem #3 "Accept, reject, cancel transfer offer without sign the records => return unexpected API response (need another clearer error)"
It returns the error that `response not signed by receiver` for the case of canceling a transfer offer. It should be `sender` instead. 
Other issues are fixed and verified.

**Comment by nodestory** [comment]
Fixed at: 89ab3b3
