### ISSUE TITLE
[SDK - Go] Account related issues

### ISSUE THREAD

**Issue by vienlt** [bitmark-inc/bitmark-sdk-go#6]
- [x] The interface `account.IsValidAccountNumber` is not available as described in the [sdk-doc](https://sdk-docs.bitmark.com/?go#account-utility-functions)

- [x] No error is returned while importing account from wrong network seeds or recovery phrases.

- [x] It is currently allowing users to parse an account of another network (expect an error returned instead).

**Comment by nodestory** [comment]
- [x] `ValidAccountNumber` is provided
- [x] `ParseAccountNumber` is removed because we don't have the use case of extracting public key now
- [x] disable account recovery from different network

**Comment by nodestory** [comment]
Fixed at: 4fda7d3dda9c1143e59c524d1fe8a7c99600f890

**Comment by vienlt** [comment]
@nodestory:  
`ValidAccountNumber is provided` - the actual provided interface is `ValidateAccountNumber`

**Comment by vienlt** [comment]
@nodestory: The interface of importing account from recovery phrase doesn't work for Chinese recovery phrase. Could you check?

**Comment by vienlt** [comment]
@nodestory: About the problem that importing account from recovery phrase doesn't work for Chinese recovery phrase, it happens only for the v1 account ( 24 words)

**Comment by nodestory** [comment]
Fixed at: 6a3d572

**Comment by vienlt** [comment]
@nodestory: The method `Account.RecoveryPhrase(language.TraditionalChinese)` is now returning English phrase for the account v1.

**Comment by nodestory** [comment]
Fixed at: d873e18

**Comment by vienlt** [comment]
All tested and passed with the commit `	github.com/bitmark-inc/bitmark-sdk-go v0.2.1-0.20190731061430-d873e18cd84d`

**Comment by nodestory** [comment]
test
